global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'loanease'
    static_configs:
      - targets: ['app:3000']

  - job_name: 'node'
    static_configs:
      - targets: ['app:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml' 