apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanease
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loanease
  template:
    metadata:
      labels:
        app: loanease
    spec:
      containers:
      - name: loanease
        image: loanease:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: host
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 