name: Monitoring

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    environment: production

    env:
      API_URL: ${{ secrets.SERVER_API_URL }}
      DB_URL: ${{ secrets.SERVER_DB_URL }}
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - name: Check API health
      uses: jtalk/url-health-check-action@v3
      with:
        url: ${{ env.API_URL }}
        max-attempts: 3
        retry-delay: 5s

    - name: Check database connection
      uses: jtalk/url-health-check-action@v3
      with:
        url: ${{ env.DB_URL }}
        max-attempts: 3
        retry-delay: 5s

    - name: Send notification on failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ env.WEBHOOK_URL }}
        SLACK_COLOR: 'danger'
        SLACK_MESSAGE: 'Health check failed!'

